#!/usr/bin/env bash

icon="$HOME/.config/i3/scripts/archlinux.png"
tmpbg='/tmp/screen.png'

#res=$(xdpyinfo | grep 'dimensions' | grep -oE '[0-9]+x[0-9]+' | head -1)
#res=(${res//x/ })
#centerx=$((${res[0]} / 2))
#centery=$((${res[1]} / 2))
#radiusx=$((centerx + 120))

scrot "$tmpbg"
convert "$tmpbg" -scale 5% -scale 2000% "$tmpbg"
#convert "$tmpbg" -draw "fill rgba(0, 0, 0, 0.5) circle $centerx, $centery, $radiusx, $centery" "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
