#!/bin/bash

rectangles=" "
SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
for RES in $SR; do
    SRA=(${RES//[x+]/ })
    CX=$((${SRA[2]} + 30))
    CY=$((${SRA[1]} - 30))
    rectangles+="rectangle $CX,$CY $((CX+280)),$((CY-80)) "
done

TMPBG=/tmp/screen.png
scrot $TMPBG \
    && convert $TMPBG \
        -scale 10% \
        -scale 1000% \
        -draw "fill rgba(0, 0, 0, 0.5) $rectangles" \
        $TMPBG

i3lock \
    -i $TMPBG \
    --clock \
    --radius=25 --ring-width=4 --indpos="x+260:h-70" \
    --timepos="ix-150:iy+5" --timecolor="ffffffff" \
    #--datepos="tx-10:ty+20" --datecolor="ffffffff" \
    #--insidecolor=00000000 --ringcolor=ffffffff --line-uses-inside \
    #--keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
    #--insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
    #--ringvercolor=ffffffff --ringwrongcolor=ffffffff \
    # --veriftext="" --wrongtext="" \

rm $TMPBG
