## Set path

# conda
export PATH=$HOME/miniconda3/bin:$PATH

# yarn
export PATH=$HOME/.yarn/bin:$PATH

# rust
export PATH=$HOME/.cargo/bin:$PATH

# TeX Live
export PATH=/usr/local/texlive/2018/bin/x86_64-linux:$PATH

# remove duplicate paths
# typeset -aU path


## Startx
if [[ ! $TMUX && ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
fi
