export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"
ZSH_CUSTOM=~/.oh-my-zsh/custom

DISABLE_AUTO_TITLE="true"

plugins=(alias export eval function git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

