export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"
ZSH_CUSTOM=~/.oh-my-zsh/custom

DISABLE_AUTO_TITLE="true"

plugins=(alias export function eval git tmux colored-man-pages colorize extract zsh-nvm)

source $ZSH/oh-my-zsh.sh
