export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"
ZSH_CUSTOM=~/.dotfiles/zsh/custom

DISABLE_AUTO_TITLE="true"

plugins=(alias export eval function git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
